TRUNCATE otps;

ALTER TABLE otps ADD COLUMN IF NOT EXISTS "failedAttempts" smallint NOT NULL DEFAULT 0;

ALTER TABLE otps ADD COLUMN IF NOT EXISTS "codeHash" varchar(64);

ALTER TABLE otps DROP COLUMN IF EXISTS code;

ALTER TABLE otps ALTER COLUMN "codeHash" SET NOT NULL;
